### ISSUE TITLE
CRITICAL: CarRepairShop breaks ISP by depending on AutomobilePlatform

### ISSUE THREAD

**Issue by radams78** [willayy/TDA553-lab1#10]
CarRepairShop has AutomobilePlatform as a component but does not use most of its methods (platformPlus1, platformMinus1, etc.) It is also not semantically correct that a RepairShop contains a Platform.

Try to find a design where CarRepairShop and CarTransporter delegate to a class that holds the common code for loading and unloading cars, while CarTransporter and Scania delegate to a different class that holds the common code for raising and lowering a platform.

https://github.com/willayy/TDA553-lab1/blob/2c84dec901c6f81005eec4dbe8ca100ae1ea9ab5/model/CarRepairShop.java#L10

**Comment by willayy** [comment]
@radams78 so CarTransporter delegets to both the theoretical "CarLoader" and "PlatformManager" classes?

**Comment by willayy** [comment]
@radams78 solved the issue with a class called CarLoadable, Automobile platform and Repairshop delegates to this instead of Repairshop delegating to Automobile platform.

**Comment by willayy** [comment]
@radams78 this issue is fixed, check lab 2 b
