### ISSUE TITLE
Bug in gas and brake methods

### ISSUE THREAD

**Issue by radams78** [willayy/TDA553-lab1#13]
If currentSpeed is enginePower - 0.5 * speedFactorc, I should be able to increase the speed with gas(0.25) to take it to enginePower - 0.25 * speedFactor. Currently this is blocked by speedIncrementationAllowed

https://github.com/willayy/TDA553-lab1/blob/2c84dec901c6f81005eec4dbe8ca100ae1ea9ab5/model/Vehicle.java#L102-L107

**Comment by willayy** [comment]
@radams78  Made it so speedIncrementationAllowed() takes an argument of double amount when considering if the incrementation/decrementatio is allowed or not, will post this in a version b as a package with other solutions when they are ready!
