### ISSUE TITLE
Remove constants x and y in Moveables

### ISSUE THREAD

**Issue by radams78** [willayy/TDA553-lab1#2]
The constants x and y are never used and can be removed.

Note: An interface cannot have instance variables. These "variables" x and y are not inherited by the classes that implement the interface. Variables in interfaces are simply constants.

https://github.com/willayy/TDA553-lab1/blob/4cf929acaf5f2086e6f4888a6d1aebea13414499/Movables.java#L5-L6

**Comment by willayy** [comment]
done
