### ISSUE TITLE
CRITICAL: Possible to set speed > enginePower by calling gas

### ISSUE THREAD

**Issue by radams78** [willayy/TDA553-lab1#4]
Calling gas(1) 101 times on a Saab95 will result in currentSpeed = 126.25. Hint: Your method speedIncrementationAllowed() checks the speed before increase, not the speed after increase.

https://github.com/willayy/TDA553-lab1/blob/4cf929acaf5f2086e6f4888a6d1aebea13414499/Saab95.java#L31-L38

**Comment by willayy** [comment]
@radams78 done.
