### ISSUE TITLE
CRITICAL: Duplicated code between Saab95 and Volvo240

### ISSUE THREAD

**Issue by radams78** [willayy/TDA553-lab1#6]
There is still some duplicated code in the code for incrementSpeed and decrementSpeed in Saab95 and Volvo240. Try to put the common code into Car. (Hint: Fix the bugs allowing speed to go <0 or >enginePower first.)

https://github.com/willayy/TDA553-lab1/blob/4cf929acaf5f2086e6f4888a6d1aebea13414499/Saab95.java#L30-L48

**Comment by willayy** [comment]
@radams78 done.
